// Export all handler modules
export { registerTojiHandlers } from './toji.handlers'
export { registerTojiEventForwarding } from './toji-events.handlers'
export { registerProjectHandlers } from './project.handlers'
export { registerWindowHandlers } from './window.handlers'
export { registerDiscordHandlers } from './discord.handlers'
export { registerBinaryHandlers } from './binary.handlers'
export { registerLoggerHandlers } from './logger.handlers'
export { registerOpencodeHandlers } from './opencode.handlers'
export { registerVoiceHandlers, cleanupVoiceServices } from './voice.handlers'
