name: Build All Platforms

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            file-pattern: '*.dmg'
          - os: windows-latest
            platform: win
            file-pattern: '*.exe'
          - os: ubuntu-latest
            platform: linux
            file-pattern: '*.AppImage'

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python setuptools
        run: pip install setuptools

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:${{ matrix.platform }} -- --publish never

      - name: Upload to Release (no artifacts)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.file-pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
