name: Build All Platforms

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            artifact-name: macos-dmg
            artifact-path: dist/*.dmg
          - os: windows-latest
            platform: win
            artifact-name: windows-exe
            artifact-path: dist/*.exe
          - os: ubuntu-latest
            platform: linux
            artifact-name: linux-appimage
            artifact-path: dist/*.AppImage

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python setuptools
        run: pip install setuptools

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:${{ matrix.platform }} -- --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          retention-days: 1  # Delete artifacts after 1 day (only needed for release creation)

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-dmg

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-exe

      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-appimage

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.dmg
            *.exe
            *.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
